name: CI/CD Pipeline

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Lint-and-Test:
    runs-on: ubuntu-latest
    outputs:
      coverage-generated: ${{ steps.tests.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run flake8 linting
        run: flake8 src/app.py

      - name: Run unit tests with coverage
        id: tests
        run: |
          coverage run -m pytest tests/
          coverage xml

  SonarCloud-CodeQuality-Analysis:
    runs-on: ubuntu-latest
    needs: Lint-and-Test
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.python.version=3.9
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.verbose=true

  SNYK-StaticSecurity-Analysis:
    runs-on: ubuntu-latest
    needs: Lint-and-Test
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check IAC files for issues
        uses: snyk/actions/iac@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  Build-and-deploy:
    runs-on: ubuntu-latest
    needs: [SonarCloud-CodeQuality-Analysis, SNYK-StaticSecurity-Analysis]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag and short SHA
        id: set_tag
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            TAG="latest-${SHORT_SHA}"
          else
            TAG="dev-${SHORT_SHA}"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "TAG=$TAG"
          echo "SHORT_SHA=$SHORT_SHA"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Multi-Arch Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}:${{ env.TAG }}

      # --- Kustomize Install ---
      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      # --- UPDATE IMAGE IN MANIFESTS REPO ---
      - name: Update image in manifests repo
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          ENVIRONMENT="development"
          if [[ "$BRANCH_NAME" == "main" ]]; then
            ENVIRONMENT="production"
          fi

          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"

          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/eli-pavlov/github-actions-cicd-manifests.git
          cd github-actions-cicd-manifests/manifests/overlays/$ENVIRONMENT

          # --- Kustomize: update image tag! ---
          kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}:${{ env.TAG }}

          git add kustomization.yaml
          git commit -m "CI: Update image tag to '${{ env.TAG }}' (${{ env.SHORT_SHA }}) for $ENVIRONMENT" || echo "Nothing to commit"
          git push

  Notify-Slack:
    runs-on: ubuntu-latest
    if: always()
    needs: Build-and-deploy
    steps:
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          STATUS="${{ needs.Build-and-deploy.result }}"
          if [[ "$STATUS" == "success" ]]; then
            COLOR="#36a64f"
            MESSAGE="✅ *Build and deploy succeeded* on *${{ github.ref_name }}*"
          elif [[ "$STATUS" == "failure" ]]; then
            COLOR="#ff0000"
            MESSAGE="❌ *Build or deploy failed* on *${{ github.ref_name }}*"
          else
            COLOR="#cccccc"
            MESSAGE="ℹ️ *Build result: $STATUS* on *${{ github.ref_name }}*"
          fi

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"attachments\":[{\"color\":\"$COLOR\",\"text\":\"$MESSAGE\"}]}" \
            $SLACK_WEBHOOK_URL
